version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dev.db
      - JWT_SECRET=dev-secret-key
      - FRONTEND_URL=http://localhost:5173
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_xxx}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_xxx}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=dev@maiway.com
    volumes:
      - ./app:/app/app
      - ./dev.db:/app/dev.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  db-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=maiway_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_dev_data: